/*
 * NXP MCX N INPUTMUX (input multiplexer / trigger routing) — bring-up model.
 *
 * Permissive register-backed model.  Every INPUTMUX register is a routing
 * selector (__IO) or a write-only SET/CLR/TOG alias (__O); all reset to 0 and
 * have no externally-observable behavior in emulation, so storing and reading
 * back the written value is faithful.  Offsets from the MCXN947 CMSIS header
 * (INPUTMUX_Type, base 0x40006000, registers up to offset 0x7B8).
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
#include "qemu/osdep.h"
#include "hw/misc/mcxn_inputmux.h"
#include "hw/core/irq.h"
#include "hw/core/qdev.h"
#include "migration/vmstate.h"

/*
 * DMAn_REQ_ENABLE{0..3}: one bit per eDMA request source, with the usual NXP
 * SET/CLR/TOG write aliases.  RM 26.5.1.56: "DMA request 0-31 enable for DMA0.  One
 * bit per request.  0: DMA request to DMA0 and response from DMA0 are blocked.
 * 1: DMA request and response are enabled for DMA0."
 *
 *   DMA0_REQ_ENABLE0 @0x700  (SET 0x704, CLR 0x708, TOG 0x70C)
 *   DMA0_REQ_ENABLE1 @0x710 ... DMA0_REQ_ENABLE3 @0x730
 *   DMA1_REQ_ENABLE0 @0x780 ... DMA1_REQ_ENABLE3 @0x7B0
 *
 * Reset (RM): FFFF_FFFF, FFFF_FFFF, FFFF_FFFF, 03FF_FFFF -- ALL 122 REQUEST LINES
 * ENABLED OUT OF RESET.  That reset value is why nothing broke while this was
 * unmodelled: the gate is open by default, so every stock example still worked.  It
 * is also exactly why it was worth modelling -- a guest that CLOSES a gate expects
 * the request to stop, and in an ungated model it does not.  The model was MORE
 * PERMISSIVE THAN THE SILICON, which ships the bug to the board.
 */
/*
 * ADC trigger selectors.  RM/CMSIS: ADC0_TRIG[4] @0x280 (step 4), ADC1_TRIG[4] @0x2C0.
 * Reset value 0x7F = NO INPUT CONNECTED -- which is why a zero reset here is a real
 * bug and not a harmless default: 0 NAMES INPUT 0, and 0x7F names nothing.
 */
#define IM_ADC0_TRIG     0x280
#define IM_ADC1_TRIG     0x2C0
#define IM_TRIG_SEL_MASK 0x7Fu
#define IM_TRIG_NONE     0x7Fu

/*
 * DACn_TRIG: one 6-bit trigger selector per DAC (reset 0x3F = NO INPUT).  DAC0 @0x300,
 * DAC1 @0x320, DAC2 @0x340 (regular 0x20 step).  A routed source advances the DAC's
 * output FIFO (waveform generation paced by a timer/PWM).
 */
#define IM_DAC0_TRIG      0x300
#define IM_DAC_TRIG_STEP  0x20
#define IM_TRIG6_MASK     0x3Fu
#define IM_TRIG6_NONE     0x3Fu

#define IM_DMA0_REQ_ENABLE0  0x700
#define IM_DMA1_REQ_ENABLE0  0x780
#define IM_REQ_ENABLE_STRIDE 0x010   /* per 32-bit bank: reg, SET, CLR, TOG */
#define IM_REQ_ENABLE_BANKS  4

/*
 * INPUTMUX reset values, straight out of the MCX N RM's register map.
 * DERIVED, NOT INVENTED -- generated by the same extractor that backs
 * tests/mcxn-reset-values, whose golden IS the reference manual.
 */
static const struct { uint16_t off; uint32_t val; } im_reset[] = {
    { 0x000, 0x0000007Fu },   /* SCT0_INMUX0 */
    { 0x004, 0x0000007Fu },   /* SCT0_INMUX1 */
    { 0x008, 0x0000007Fu },   /* SCT0_INMUX2 */
    { 0x00C, 0x0000007Fu },   /* SCT0_INMUX3 */
    { 0x010, 0x0000007Fu },   /* SCT0_INMUX4 */
    { 0x014, 0x0000007Fu },   /* SCT0_INMUX5 */
    { 0x018, 0x0000007Fu },   /* SCT0_INMUX6 */
    { 0x01C, 0x0000007Fu },   /* SCT0_INMUX7 */
    { 0x020, 0x0000007Fu },   /* CTIMER0CAP0 */
    { 0x024, 0x0000007Fu },   /* CTIMER0CAP1 */
    { 0x028, 0x0000007Fu },   /* CTIMER0CAP2 */
    { 0x02C, 0x0000007Fu },   /* CTIMER0CAP3 */
    { 0x030, 0x0000007Fu },   /* TIMER0TRIG */
    { 0x040, 0x0000007Fu },   /* CTIMER1CAP0 */
    { 0x044, 0x0000007Fu },   /* CTIMER1CAP1 */
    { 0x048, 0x0000007Fu },   /* CTIMER1CAP2 */
    { 0x04C, 0x0000007Fu },   /* CTIMER1CAP3 */
    { 0x050, 0x0000007Fu },   /* TIMER1TRIG */
    { 0x060, 0x0000007Fu },   /* CTIMER2CAP0 */
    { 0x064, 0x0000007Fu },   /* CTIMER2CAP1 */
    { 0x068, 0x0000007Fu },   /* CTIMER2CAP2 */
    { 0x06C, 0x0000007Fu },   /* CTIMER2CAP3 */
    { 0x070, 0x0000007Fu },   /* TIMER2TRIG */
    { 0x0C0, 0x0000007Fu },   /* PINTSEL0 */
    { 0x0C4, 0x0000007Fu },   /* PINTSEL1 */
    { 0x0C8, 0x0000007Fu },   /* PINTSEL2 */
    { 0x0CC, 0x0000007Fu },   /* PINTSEL3 */
    { 0x0D0, 0x0000007Fu },   /* PINTSEL4 */
    { 0x0D4, 0x0000007Fu },   /* PINTSEL5 */
    { 0x0D8, 0x0000007Fu },   /* PINTSEL6 */
    { 0x0DC, 0x0000007Fu },   /* PINTSEL7 */
    { 0x1A0, 0x0000007Fu },   /* CTIMER3CAP0 */
    { 0x1A4, 0x0000007Fu },   /* CTIMER3CAP1 */
    { 0x1A8, 0x0000007Fu },   /* CTIMER3CAP2 */
    { 0x1AC, 0x0000007Fu },   /* CTIMER3CAP3 */
    { 0x1B0, 0x0000007Fu },   /* TIMER3TRIG */
    { 0x1C0, 0x0000007Fu },   /* CTIMER4CAP0 */
    { 0x1C4, 0x0000007Fu },   /* CTIMER4CAP1 */
    { 0x1C8, 0x0000007Fu },   /* CTIMER4CAP2 */
    { 0x1CC, 0x0000007Fu },   /* CTIMER4CAP3 */
    { 0x1D0, 0x0000007Fu },   /* TIMER4TRIG */
    { 0x260, 0x0000003Fu },   /* CMP0_TRIG */
    { 0x2C0, 0x0000007Fu },   /* ADC1_TRIG0 */
    { 0x2C4, 0x0000007Fu },   /* ADC1_TRIG1 */
    { 0x2C8, 0x0000007Fu },   /* ADC1_TRIG2 */
    { 0x2CC, 0x0000007Fu },   /* ADC1_TRIG3 */
    { 0x300, 0x0000003Fu },   /* DAC0_TRIG */
    { 0x320, 0x0000003Fu },   /* DAC1_TRIG */
    { 0x340, 0x0000003Fu },   /* DAC2_TRIG */
    { 0x360, 0x0000003Fu },   /* QDC0_TRIG */
    { 0x364, 0x0000003Fu },   /* QDC0_HOME */
    { 0x368, 0x0000003Fu },   /* QDC0_INDEX */
    { 0x36C, 0x0000003Fu },   /* QDC0_PHASEB */
    { 0x370, 0x0000003Fu },   /* QDC0_PHASEA */
    { 0x380, 0x0000003Fu },   /* QDC1_TRIG */
    { 0x384, 0x0000003Fu },   /* QDC1_HOME */
    { 0x388, 0x0000003Fu },   /* QDC1_INDEX */
    { 0x38C, 0x0000003Fu },   /* QDC1_PHASEB */
    { 0x390, 0x0000003Fu },   /* QDC1_PHASEA */
    { 0x420, 0x00000007u },   /* PWM0_EXT_CLK */
    { 0x424, 0x00000007u },   /* PWM1_EXT_CLK */
    { 0x480, 0x0000000Fu },   /* USBFS_TRIG */
    { 0x4A0, 0x00000003u },   /* TSI_TRIG */
    { 0x4E0, 0x0000003Fu },   /* CMP1_TRIG */
    { 0x500, 0x0000003Fu },   /* CMP2_TRIG */
    { 0x5A0, 0x0000003Fu },   /* FLEXCOMM0_TRIG */
    { 0x5C0, 0x0000003Fu },   /* FLEXCOMM1_TRIG */
    { 0x5E0, 0x0000003Fu },   /* FLEXCOMM2_TRIG */
    { 0x600, 0x0000003Fu },   /* FLEXCOMM3_TRIG */
    { 0x620, 0x0000003Fu },   /* FLEXCOMM4_TRIG */
    { 0x640, 0x0000003Fu },   /* FLEXCOMM5_TRIG */
    { 0x660, 0x0000003Fu },   /* FLEXCOMM6_TRIG */
    { 0x680, 0x0000003Fu },   /* FLEXCOMM7_TRIG */
    { 0x6A0, 0x0000003Fu },   /* FLEXCOMM8_TRIG */
    { 0x6C0, 0x0000003Fu },   /* FLEXCOMM9_TRIG */
    { 0x6E0, 0x0000007Fu },   /* FLEXIO_TRIG0 */
    { 0x6E4, 0x0000007Fu },   /* FLEXIO_TRIG1 */
    { 0x6E8, 0x0000007Fu },   /* FLEXIO_TRIG2 */
    { 0x6EC, 0x0000007Fu },   /* FLEXIO_TRIG3 */
    { 0x6F0, 0x0000007Fu },   /* FLEXIO_TRIG4 */
    { 0x6F4, 0x0000007Fu },   /* FLEXIO_TRIG5 */
    { 0x6F8, 0x0000007Fu },   /* FLEXIO_TRIG6 */
    { 0x6FC, 0x0000007Fu },   /* FLEXIO_TRIG7 */
    { 0x700, 0xFFFFFFFFu },   /* DMA0_REQ_ENABLE0 */
    { 0x710, 0xFFFFFFFFu },   /* DMA0_REQ_ENABLE1 */
    { 0x720, 0xFFFFFFFFu },   /* DMA0_REQ_ENABLE2 */
    { 0x730, 0x03FFFFFFu },   /* DMA0_REQ_ENABLE3 */
    { 0x780, 0xFFFFFFFFu },   /* DMA1_REQ_ENABLE0 */
    { 0x790, 0xFFFFFFFFu },   /* DMA1_REQ_ENABLE1 */
    { 0x7A0, 0xFFFFFFFFu },   /* DMA1_REQ_ENABLE2 */
    { 0x7B0, 0x03FFFFFFu },   /* DMA1_REQ_ENABLE3 */
};

/* Map an offset to (dma, bank, alias) or return false. */
static bool im_decode_req_enable(hwaddr off, int *dma, int *bank, int *alias)
{
    hwaddr rel;

    if (off >= IM_DMA0_REQ_ENABLE0 &&
        off < IM_DMA0_REQ_ENABLE0 + IM_REQ_ENABLE_BANKS * IM_REQ_ENABLE_STRIDE) {
        *dma = 0;
        rel = off - IM_DMA0_REQ_ENABLE0;
    } else if (off >= IM_DMA1_REQ_ENABLE0 &&
               off < IM_DMA1_REQ_ENABLE0 + IM_REQ_ENABLE_BANKS * IM_REQ_ENABLE_STRIDE) {
        *dma = 1;
        rel = off - IM_DMA1_REQ_ENABLE0;
    } else {
        return false;
    }
    *bank  = rel / IM_REQ_ENABLE_STRIDE;
    *alias = (rel % IM_REQ_ENABLE_STRIDE) / 4;   /* 0=reg 1=SET 2=CLR 3=TOG */
    return true;
}

/* Push a bank's 32 gate levels out to the eDMA. */
static void im_push_req_enable(MCXNInputMuxState *s, int dma, int bank)
{
    uint32_t base = (dma ? IM_DMA1_REQ_ENABLE0 : IM_DMA0_REQ_ENABLE0)
                    + bank * IM_REQ_ENABLE_STRIDE;
    uint32_t v = s->regs[base / 4];
    int i;

    for (i = 0; i < 32; i++) {
        int src = bank * 32 + i;

        if (src < MCXN_INPUTMUX_NREQ) {
            qemu_set_irq(s->dma_req_enable[dma][src], (v >> i) & 1);
        }
    }
}

static uint64_t mcxn_inputmux_read(void *opaque, hwaddr offset, unsigned size)
{
    MCXNInputMuxState *s = MCXN_INPUTMUX(opaque);

    return s->regs[offset / 4];
}

/*
 * A trigger source fired.  Forward the EDGE to every destination whose selector
 * currently names this source.
 *
 * ⚠ THIS IS THE HALF OF INPUTMUX THAT WAS MISSING, AND ITS ABSENCE WAS SILENT.  A
 * guest could attach LPTMR0 to ADC0_TRIG[0], start the timer, arm the ADC, and wait
 * forever: the timer ticked, the trigger went NOWHERE, and no conversion ever
 * happened.  Nothing logged, nothing faulted -- the stock lpadc/edma example just
 * sat there.  A router that routes nothing looks exactly like a router.
 */
/*
 * The physical trigger source that (destination ADC, selector value) connects to.
 *
 * Almost every selector is identity -- the selector value IS the source id.  The
 * exception is CTIMER3/4 -> ADC: ADC0_TRIG=8/9 name Ctimer3M3 / Ctimer4M3, but
 * ADC1_TRIG=8/9 name Ctimer3M2 / Ctimer4M1 (a PER-DESTINATION connection, from NXP's
 * INPUTMUX table).  Those two ADC1-facing lines carry distinct source ids, so the same
 * written selector value routes to the correct physical match line for each ADC -- a
 * shared-selector model that ignored this would fire ADC1 on the wrong CTIMER match.
 */
static uint32_t im_adc_sel_to_src(int adc, uint32_t sel)
{
    if (adc == 1) {
        if (sel == 8) {
            return MCXN_INPUTMUX_SRC_CTIMER3_M2;
        }
        if (sel == 9) {
            return MCXN_INPUTMUX_SRC_CTIMER4_M1;
        }
    }
    return sel;
}

static void mcxn_inputmux_trigger(void *opaque, int src, int level)
{
    MCXNInputMuxState *s = MCXN_INPUTMUX(opaque);
    int adc, t;

    if (!level || src < 0 || src >= MCXN_INPUTMUX_NTRIG_SRC) {
        return;                      /* triggers are edges, not levels */
    }

    for (adc = 0; adc < MCXN_INPUTMUX_NADC; adc++) {
        uint32_t base = adc ? IM_ADC1_TRIG : IM_ADC0_TRIG;

        for (t = 0; t < MCXN_INPUTMUX_NADC_TRIG; t++) {
            uint32_t sel = s->regs[(base + t * 4) / 4] & IM_TRIG_SEL_MASK;

            if (sel != IM_TRIG_NONE &&
                im_adc_sel_to_src(adc, sel) == (uint32_t)src) {
                qemu_irq_pulse(s->adc_trig[adc][t]);
            }
        }
    }

    /* DACn_TRIG: one 6-bit selector per DAC; a match advances that DAC's output FIFO. */
    for (t = 0; t < MCXN_INPUTMUX_NDAC; t++) {
        uint32_t sel = s->regs[(IM_DAC0_TRIG + t * IM_DAC_TRIG_STEP) / 4]
                       & IM_TRIG6_MASK;

        if (sel != IM_TRIG6_NONE && sel == (uint32_t)src) {
            qemu_irq_pulse(s->dac_trig[t]);
        }
    }
}

static void mcxn_inputmux_write(void *opaque, hwaddr offset, uint64_t value,
                                unsigned size)
{
    MCXNInputMuxState *s = MCXN_INPUTMUX(opaque);
    int dma, bank, alias;

    if (im_decode_req_enable(offset, &dma, &bank, &alias)) {
        uint32_t base = (dma ? IM_DMA1_REQ_ENABLE0 : IM_DMA0_REQ_ENABLE0)
                        + bank * IM_REQ_ENABLE_STRIDE;
        uint32_t *reg = &s->regs[base / 4];

        switch (alias) {
        case 0: *reg  = value; break;   /* the register itself */
        case 1: *reg |= value; break;   /* SET */
        case 2: *reg &= ~(uint32_t)value; break;   /* CLR */
        case 3: *reg ^= value; break;   /* TOG */
        default: break;
        }
        im_push_req_enable(s, dma, bank);
        return;
    }

    s->regs[offset / 4] = value;
}

static const MemoryRegionOps mcxn_inputmux_ops = {
    .read = mcxn_inputmux_read,
    .write = mcxn_inputmux_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid.min_access_size = 4,
    .valid.max_access_size = 4,
    .impl.min_access_size = 4,
    .impl.max_access_size = 4,
};

static void mcxn_inputmux_reset(DeviceState *dev)
{
    MCXNInputMuxState *s = MCXN_INPUTMUX(dev);
    int i;

    memset(s->regs, 0, sizeof(s->regs));

    /*
     * Reset values, TAKEN FROM THE RM'S REGISTER MAP, not from zero.
     *
     * A SELECTOR THAT RESETS TO 0 IS NOT "UNCONFIGURED" -- IT NAMES INPUT 0.  The
     * real reset is 0x7F (or 0x3F on the 6-bit selectors) and that value means NO
     * INPUT CONNECTED.  Reading 0 tells the guest a source is already attached, and
     * a guest that reads-modifies-writes a selector inherits a connection nobody
     * made.
     *
     * DMAn_REQ_ENABLE resets to all-ones: every eDMA request line ENABLED.  A zero
     * there would BLOCK EVERY PERIPHERAL-TRIGGERED TRANSFER ON THE CHIP.
     *
     * Generated from the reference manual, so it cannot drift into invention.
     */
    for (i = 0; i < (int)ARRAY_SIZE(im_reset); i++) {
        s->regs[im_reset[i].off / 4] = im_reset[i].val;
    }
}

static void mcxn_inputmux_realize(DeviceState *dev, Error **errp)
{
    MCXNInputMuxState *s = MCXN_INPUTMUX(dev);

    memory_region_init_io(&s->iomem, OBJECT(s), &mcxn_inputmux_ops, s,
                          TYPE_MCXN_INPUTMUX, MCXN_INPUTMUX_SIZE);
    sysbus_init_mmio(SYS_BUS_DEVICE(dev), &s->iomem);

    /* One gate line per eDMA request source, per eDMA (DMA0 then DMA1). */
    qdev_init_gpio_out_named(dev, s->dma_req_enable[0], "dma0-req-enable",
                             MCXN_INPUTMUX_NREQ);
    qdev_init_gpio_out_named(dev, s->dma_req_enable[1], "dma1-req-enable",
                             MCXN_INPUTMUX_NREQ);

    /* Trigger routing: one input per selector value, one output per ADC trigger. */
    qdev_init_gpio_in_named(dev, mcxn_inputmux_trigger, "trig-in",
                            MCXN_INPUTMUX_NTRIG_SRC);
    qdev_init_gpio_out_named(dev, s->adc_trig[0], "adc0-trig",
                             MCXN_INPUTMUX_NADC_TRIG);
    qdev_init_gpio_out_named(dev, s->adc_trig[1], "adc1-trig",
                             MCXN_INPUTMUX_NADC_TRIG);
    qdev_init_gpio_out_named(dev, s->dac_trig, "dac-trig", MCXN_INPUTMUX_NDAC);
}

static const VMStateDescription vmstate_mcxn_inputmux = {
    .name = TYPE_MCXN_INPUTMUX,
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (const VMStateField[]) {
        VMSTATE_UINT32_ARRAY(regs, MCXNInputMuxState, MCXN_INPUTMUX_SIZE / 4),
        VMSTATE_END_OF_LIST()
    },
};

static void mcxn_inputmux_class_init(ObjectClass *klass, const void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);

    dc->realize = mcxn_inputmux_realize;
    device_class_set_legacy_reset(dc, mcxn_inputmux_reset);
    dc->vmsd = &vmstate_mcxn_inputmux;
}

static const TypeInfo mcxn_inputmux_types[] = {
    {
        .name          = TYPE_MCXN_INPUTMUX,
        .parent        = TYPE_SYS_BUS_DEVICE,
        .instance_size = sizeof(MCXNInputMuxState),
        .class_init    = mcxn_inputmux_class_init,
    },
};

DEFINE_TYPES(mcxn_inputmux_types)
